(function(g){var window=this;var nHa=function(a,b){return g.Tb(a,b)},Z5=function(a,b,c){a.C.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.hn(a.C,b,c)},oHa=function(a,b){var c=[];
g.$i(b,function(d){try{var e=g.Wn.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Vn(e)&&c.push(d)},a);
return c},pHa=function(a,b){var c=oHa(a,b);
g.Fb(c,function(d){g.Wn.prototype.remove.call(this,d)},a)},qHa=function(a){if(a.ae){if(a.ae.locationOverrideToken)return{locationOverrideToken:a.ae.locationOverrideToken};
if(null!=a.ae.latitudeE7&&null!=a.ae.longitudeE7)return{latitudeE7:a.ae.latitudeE7,longitudeE7:a.ae.longitudeE7}}return null},rHa=function(a,b){g.nb(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},sHa=function(a,b){var c=b instanceof g.Fc?b:g.Lc(b,/^data:image\//i.test(b));
a.src=g.Gc(c)},c6=function(){},tHa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},uHa=function(a){if(a.rf&&"function"==typeof a.rf)return a.rf();
if("string"===typeof a)return a.split("");if(g.Ra(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},vHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ra(a)||"string"===typeof a)g.Fb(a,b,void 0);else{if(a.xg&&"function"==typeof a.xg)var c=a.xg();else if(a.rf&&"function"==typeof a.rf)c=void 0;else if(g.Ra(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=uHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},wHa=function(a,b,c,d){var e=new g.Wm(null,void 0);
a&&g.Xm(e,a);b&&g.Ym(e,b);c&&g.Zm(e,c);d&&(e.B=d);return e},d6=function(a,b){g.Io[a]=!0;
var c=g.Go();c&&c.publish.apply(c,arguments);g.Io[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Tm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",xHa(this,a.capabilities||""),yHa(this,a.experiments||""))},xHa=function(a,b){a.capabilities.clear();
g.Je(b.split(","),g.Va(nHa,zHa)).forEach(function(c){a.capabilities.add(c)})},yHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},AHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},BHa=function(a){return new f6(a)},CHa=function(a){return Array.isArray(a)?g.Pc(a,BHa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+g.Pc(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},DHa=function(a){return g.Pc(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.jb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.jb(a,function(c){return g6(c,b)})},EHa=function(){var a=(0,g.qt)();
a&&pHa(a,a.u.Si(!0))},m6=function(){var a=g.ut("yt-remote-connected-devices")||[];
g.Cb(a);return a},FHa=function(a){if(g.ob(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Pc(a,function(d,e){return 0==e?d:d.substring(c.length)})},GHa=function(a){g.tt("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.ut("yt-remote-device-id");a||(a=j6(),g.tt("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.nb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.nb(a,b);g.wt()&&g.Eb(a,b);a=FHa(a);if(g.ob(a))try{g.uq("remote_sid")}catch(c){}else try{g.sq("remote_sid",a.join(","),-1)}catch(c){}},HHa=function(){return g.ut("yt-remote-session-browser-channel")},IHa=function(){return g.ut("yt-remote-local-screens")||[]},JHa=function(){g.tt("yt-remote-lounge-token-expiration",!0,86400)},KHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Pc(IHa(),function(d){return d.loungeToken}),c=g.Pc(a,function(d){return d.loungeToken});
g.gh(c,function(d){return!g.nb(b,d)})&&JHa();
g.tt("yt-remote-local-screens",a,31536E3)},LHa=function(a,b){g.tt("yt-remote-session-browser-channel",a);
g.tt("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.nb(c,d)||c.push(d);GHa(c);p6()},q6=function(a){a||(g.vt("yt-remote-session-screen-id"),g.vt("yt-remote-session-video-id"));
p6();a=m6();g.rb(a,o6());GHa(a)},MHa=function(){if(!r6){var a=g.go();
a&&(r6=new g.Qn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},NHa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},OHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?PHa(a.shift(),function(){s6(a)}):t6()},QHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},PHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.jd(d,g.jg(a));(document.head||document.documentElement).appendChild(d)},t6=function(){var a=OHa();
a&&a(!1,"No cast extension found")},SHa=function(){if(RHa){var a=2,b=OHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;PHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},THa=function(){SHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");s6(b)},u6=function(a,b,c){g.B.call(this);
this.G=null!=c?(0,g.z)(a,c):a;this.df=b;this.F=(0,g.z)(this.NI,this);this.u=!1;this.B=0;this.C=this.Va=null;this.D=[]},v6=function(a,b,c){g.B.call(this);
this.D=null!=c?a.bind(c):a;this.df=b;this.C=null;this.u=!1;this.B=0;this.Va=null},w6=function(a){a.Va=g.Rm(function(){a.Va=null;
a.u&&!a.B&&(a.u=!1,w6(a))},a.df);
var b=a.C;a.C=null;a.D.apply(null,b)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return tHa(a)},y6=function(){},z6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){A6.dispatchEvent(new UHa(A6,a))},UHa=function(a){g.Il.call(this,"statevent",a)},C6=function(){},VHa=function(){},XHa=function(a){return(a=WHa(a))?new ActiveXObject(a):new XMLHttpRequest},WHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},D6=function(a,b,c,d){this.u=a;
this.B=b;this.P=c;this.K=d||1;this.F=45E3;this.D=new g.k1(this);this.C=new g.Qm;this.C.setInterval(250)},ZHa=function(a,b,c){a.Xn=1;
a.Uj=$5(b.clone());a.hm=c;a.G=!0;YHa(a,null)},E6=function(a,b,c,d,e){a.Xn=1;
a.Uj=$5(b.clone());a.hm=null;a.G=c;e&&(a.IF=!1);YHa(a,d)},YHa=function(a,b){a.On=g.A();
F6(a);a.Jk=a.Uj.clone();a6(a.Jk,"t",a.K);a.Iq=0;a.ee=a.u.Kv(a.u.qq()?b:null);0<a.Cw&&(a.Xt=new v6((0,g.z)(a.HG,a,a.ee),a.Cw));a.D.wa(a.ee,"readystatechange",a.WP);var c=a.Fl?g.Zb(a.Fl):{};a.hm?(a.Fu="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.ee.send(a.Jk,a.Fu,a.hm,c)):(a.Fu="GET",a.IF&&!g.ze&&(c.Connection="close"),a.ee.send(a.Jk,a.Fu,null,c));a.u.uh(1)},bIa=function(a,b,c){for(var d=!0;!a.kl&&a.Iq<c.length;){var e=$Ha(a,c);
if(e==G6){4==b&&(a.kk=4,B6(15),d=!1);break}else if(e==aIa){a.kk=4;B6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.kk=1,B6(17),d=!1);a.Eh=a.Eh&&d;d||(I6(a),J6(a))},$Ha=function(a,b){var c=a.Iq,d=b.indexOf("\n",c);
if(-1==d)return G6;c=Number(b.substring(c,d));if(isNaN(c))return aIa;d+=1;if(d+c>b.length)return G6;var e=b.substr(d,c);a.Iq=d+c;return e},dIa=function(a,b){a.On=g.A();
F6(a);var c=b?window.location.hostname:"";a.Jk=a.Uj.clone();Z5(a.Jk,"DOMAIN",c);Z5(a.Jk,"t",a.K);try{a.Jh=new ActiveXObject("htmlfile")}catch(n){I6(a);a.kk=7;B6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in K6)h=K6[h];else if(h in cIa)h=K6[h]=cIa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
K6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.gd(g.jc("b/12014412"),d+"</body></html>");a.Jh.open();a.Jh.write(g.cd(c));a.Jh.close();a.Jh.parentWindow.m=(0,g.z)(a.kP,a);a.Jh.parentWindow.d=(0,g.z)(a.HE,a,!0);a.Jh.parentWindow.rpcClose=(0,g.z)(a.HE,a,!1);c=a.Jh.createElement("DIV");a.Jh.parentWindow.document.body.appendChild(c);d=g.Kc(a.Jk.toString());d=g.nd(g.Gc(d));d=g.gd(g.jc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,d);a.u.uh(1)},F6=function(a){a.pz=g.A()+a.F;
eIa(a,a.F)},eIa=function(a,b){if(null!=a.fo)throw Error("WatchDog timer not null");
a.fo=z6((0,g.z)(a.wP,a),b)},L6=function(a){a.fo&&(g.v.clearTimeout(a.fo),a.fo=null)},J6=function(a){a.u.IB()||a.kl||a.u.ls(a)},I6=function(a){L6(a);
g.ag(a.Xt);a.Xt=null;a.C.stop();g.ABa(a.D);if(a.ee){var b=a.ee;a.ee=null;b.abort();b.dispose()}a.Jh&&(a.Jh=null)},H6=function(a,b){try{a.u.zE(a,b),a.u.uh(4)}catch(c){}},gIa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;fIa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){gIa(a,b,c,d,f)},f)})}},fIa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
sHa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},N6=function(a){g.fm.call(this);
this.headers=new g.Tm;this.ba=a||null;this.C=!1;this.Y=this.u=null;this.ra=this.N="";this.G=0;this.D="";this.F=this.ia=this.P=this.ea=!1;this.K=0;this.W=null;this.Aa="";this.X=this.da=!1},hIa=function(a){return g.xe&&g.Yd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},iIa=function(a){return"content-type"==a.toLowerCase()},kIa=function(a,b){a.C=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.G=5;jIa(a);O6(a)},jIa=function(a){a.ea||(a.ea=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},mIa=function(a){if(a.C&&"undefined"!=typeof g.p1)if(a.Y[1]&&4==P6(a)&&2==a.getStatus())Q6(a,"Local request error detected and ignored");
else if(a.P&&4==P6(a))g.Rm(a.wE,0,a);else if(a.dispatchEvent("readystatechange"),4==P6(a)){Q6(a,"Request complete");a.C=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.wd(1,String(a.N));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!lIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<P6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";jIa(a)}}finally{O6(a)}}},O6=function(a,b){if(a.u){nIa(a);
var c=a.u,d=a.Y[0]?g.Oa:null;a.u=null;a.Y=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},nIa=function(a){a.u&&a.X&&(a.u.ontimeout=null);
a.W&&(g.v.clearTimeout(a.W),a.W=null)},P6=function(a){return a.u?a.u.readyState:0},R6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},Q6=function(a,b){return b+" ["+a.ra+" "+a.N+" "+a.getStatus()+"]"},oIa=function(a){this.u=a;
this.B=new y6},pIa=function(a){var b=S6(a.u,a.xo,"/mail/images/cleardot.gif");
$5(b);gIa(b.toString(),5E3,(0,g.z)(a.LH,a),3,2E3);a.uh(1)},U6=function(a){var b=a.u.P;
if(null!=b)B6(5),b?(B6(11),T6(a.u,a,!1)):(B6(12),T6(a.u,a,!0));else if(a.Qf=new D6(a,void 0,void 0,void 0),a.Qf.Fl=a.Aw,b=a.u,b=S6(b,b.qq()?a.bp:null,a.Bw),B6(5),!g.xe||g.Zd(10))a6(b,"TYPE","xmlhttp"),E6(a.Qf,b,!1,a.bp,!1);else{a6(b,"TYPE","html");var c=a.Qf;a=!!a.bp;c.Xn=3;c.Uj=$5(b.clone());dIa(c,a)}},V6=function(a,b,c){this.Ha=1;
this.u=[];this.C=[];this.D=new y6;this.K=a||null;this.P=null!=b?b:null;this.F=c||!1},qIa=function(a,b){this.u=a;
this.map=b;this.context=null},sIa=function(a,b,c,d){g.Il.call(this,"timingevent",a);
this.size=b;this.gq=d},tIa=function(a){g.Il.call(this,"serverreachability",a)},wIa=function(a){uIa(a);
if(3==a.Ha){var b=a.Lp++,c=a.Kr.clone();Z5(c,"SID",a.B);Z5(c,"RID",b);Z5(c,"TYPE","terminate");W6(a,c);b=new D6(a,a.B,b,void 0);b.Xn=2;b.Uj=$5(c.clone());sHa(new Image,b.Uj.toString());b.On=g.A();F6(b)}vIa(a)},xIa=function(a){a.kI(1,0);
a.Kr=S6(a,null,a.zw);X6(a)},uIa=function(a){a.Zj&&(a.Zj.abort(),a.Zj=null);
a.zd&&(a.zd.cancel(),a.zd=null);a.Ui&&(g.v.clearTimeout(a.Ui),a.Ui=null);Y6(a);a.Hf&&(a.Hf.cancel(),a.Hf=null);a.dk&&(g.v.clearTimeout(a.dk),a.dk=null)},yIa=function(a,b){if(0==a.Ha)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new qIa(a.UL++,b));2!=a.Ha&&3!=a.Ha||X6(a)},zIa=function(a){var b=0;
a.zd&&b++;a.Hf&&b++;return b},X6=function(a){a.Hf||a.dk||(a.dk=z6((0,g.z)(a.GE,a),0),a.Sm=0)},BIa=function(a,b){if(1==a.Ha){if(!b){a.Lp=Math.floor(1E5*Math.random());
var c=a.Lp++,d=new D6(a,"",c,void 0);d.Fl=a.Xm;var e=Z6(a),f=a.Kr.clone();Z5(f,"RID",c);Z5(f,"CVER","1");W6(a,f);ZHa(d,f,e);a.Hf=d;a.Ha=2}}else 3==a.Ha&&(b?AIa(a,b):0==a.u.length||a.Hf||AIa(a))},AIa=function(a,b){if(b)if(6<a.ll){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.Lp-1;var d=Z6(a)}else c=b.P,d=b.hm;else c=a.Lp++,d=Z6(a);var e=a.Kr.clone();Z5(e,"SID",a.B);Z5(e,"RID",c);Z5(e,"AID",a.hn);W6(a,e);c=new D6(a,a.B,c,a.Sm+1);c.Fl=a.Xm;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Hf=c;ZHa(c,e,d)},W6=function(a,b){if(a.af){var c=a.af.kB();
c&&g.Ib(c,function(d,e){Z5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.ll&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={zm:e.zm},f++){e.zm=a.u[f].u;var h=a.u[f].map;e.zm=6>=a.ll?f:e.zm-d;try{g.Ib(h,function(l){return function(m,n){c.push("req"+l.zm+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.zm+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},CIa=function(a){a.zd||a.Ui||(a.G=1,a.Ui=z6((0,g.z)(a.FE,a),0),a.Dm=0)},$6=function(a){if(a.zd||a.Ui||3<=a.Dm)return!1;
a.G++;a.Ui=z6((0,g.z)(a.FE,a),DIa(a,a.Dm));a.Dm++;return!0},T6=function(a,b,c){a.Cu=c;
a.hi=b.hj;a.F||xIa(a)},Y6=function(a){null!=a.rl&&(g.v.clearTimeout(a.rl),a.rl=null)},DIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.af&&(c=null);var d=(0,g.z)(a.FQ,a);c||(c=new g.Wm("//www.google.com/images/cleardot.gif"),$5(c));fIa(c.toString(),1E4,d)}else B6(2);EIa(a,b)},EIa=function(a,b){a.Ha=0;
a.af&&a.af.xA(b);vIa(a);uIa(a)},vIa=function(a){a.Ha=0;
a.hi=-1;if(a.af)if(0==a.C.length&&0==a.u.length)a.af.yv();else{g.ub(a.C);var b=g.ub(a.u);a.C.length=0;a.u.length=0;a.af.yv(b)}},S6=function(a,b,c){var d=g.dn(c);
if(""!=d.u)b&&g.Ym(d,b+"."+d.u),g.Zm(d,d.D);else{var e=window.location;d=wHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.No&&g.Ib(a.No,function(f,h){Z5(d,h,f)});
Z5(d,"VER",a.ll);W6(a,d);return d},FIa=function(){},GIa=function(){this.u=[];
this.B=[]},HIa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.B.call(this);
this.u=new g.F(this.dP,0,this);g.C(this,this.u);this.df=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},c7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.W=a;this.G=b;this.C=new g.Pn;this.B=new b7(this.iQ,this);this.u=null;this.Qd=!1;this.F=null;this.N="";this.P=this.D=0;this.K=[];this.Y=c;this.X=d},IIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.Cu,sessionId:a.u.B,arrayId:a.u.hn}},JIa=function(a,b){a.P=b||0;
a.B.stop();d7(a);a.u&&(3==a.u.getState()&&BIa(a.u),wIa(a.u));a.P=0},e7=function(a){return!!a.u&&3==a.u.getState()},d7=function(a){if(a.u){var b=a.X(),c=a.u.Xm||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Xm=c}},KIa=function(a,b){(a.G.loungeIdToken=b)||a.B.stop()},f7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.wd(4,a))||"";b&&(this.port=":"+b);this.domain=g.xd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Dc(a,"10.0")&&(this.B=!1))},g7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Id(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Va(a.D,d,!0),onError:g.Va(a.C,e),kg:g.Va(a.F,e)};c&&(a.dc=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.mq(b,a)},OIa=function(){var a=LIa;
MIa();i7.push(a);NIa(i7)},j7=function(a,b){MIa();
var c=i7,d=PIa(a,String(b));g.ob(c)?QIa(d):(NIa(c),g.Fb(c,function(e){e(d)}))},MIa=function(){i7||(i7=g.Na("yt.mdx.remote.debug.handlers_")||[],g.Ja("yt.mdx.remote.debug.handlers_",i7,void 0))},QIa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},NIa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];g.Fb(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},PIa=function(a,b){var c=(g.A()-RIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.O.call(this);
this.G=a;this.screens=[]},SIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},TIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Je(a.screens,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=SIa(a,b[d])||c;return c},UIa=function(a,b){var c=a.screens.length;
a.screens=g.Je(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.O.call(this);
this.G=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Va=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;p7(this);this.info("Initializing with "+i6(this.screens))},VIa=function(a){if(a.screens.length){var b=g.Pc(a.screens,function(d){return d.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.XI,a),(0,g.z)(a.WI,a))}},p7=function(a){if(g.so("deprecate_pair_servlet_enabled"))return TIa(a,[]);
var b=CHa(IHa());b=g.Je(b,function(c){return!c.uuid});
return TIa(a,b)},r7=function(a,b){KHa(g.Pc(a.screens,AHa));
b&&JHa()},t7=function(a,b){g.O.call(this);
this.G=b;var c=g.ut("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.G(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.nb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;s7("Initialized with "+g.Cj(this.u))},WIa=function(a,b,c){var d=g7(a.F,"/pairing/get_screen_availability");
h7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},u7=function(a,b){a:if(b6(b)!=b6(a.u))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Cj(a.u)),a.u=b,a.V("screenChange"));XIa(a)},v7=function(a){isNaN(a.C)||g.Fo(a.C);
a.C=g.Do((0,g.z)(a.ry,a),0<a.D&&a.D<g.A()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},YIa=function(a){var b={};
g.Fb(a.G(),function(c){c.token?b[c.token]=c.id:this.cd("Requesting availability of screen w/o lounge token.")});
return b},XIa=function(a){a=g.Qb(g.Jb(a.u,function(b){return b}));
g.Cb(a);a.length?g.tt("yt-remote-online-screen-ids",a.join(","),60):g.vt("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};ZIa(this)},aJa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Yf();if(h=(c?l6(h,c):null)||l6(h,b)){h.uuid=b;var l=x7(a,h);WIa(a.u,l,function(m){e(m?l:null)})}else c?$Ia(a,c,(0,g.z)(function(m){var n=x7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));WIa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},bJa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},$Ia=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={dc:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.mq(g7(a.F,"/pairing/get_lounge_token_batch"),e)},cJa=function(a){a.screens=a.B.Yf();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.screens))},ZIa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.eJ,a));cJa(a);a.C=CHa(g.ut("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+i6(a.C));a.u=new t7(a.F,(0,g.z)(a.Yf,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.tt("yt-remote-automatic-screen-cache",g.Pc(a.C,AHa)));y7(a);a.D[b.uuid]=b.id;g.tt("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.ut("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.O.call(this);
this.Y=c;this.P=a;this.u=b;this.K=null},A7=function(a,b){j7(a.Y,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.qR,this);this.D=(0,g.z)(this.DP,this);this.C=g.Do((0,g.z)(function(){dJa(this,null)},this),12E4)},eJa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Cj(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Oa,(0,g.z)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Cj(b))},dJa=function(a,b){g.Fo(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.Nt,a),d=(0,g.z)(a.hg,a);a.BB(b,c,d,5)}}else a.hg(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.G=null;this.N="";this.ba=c;this.W=null;this.F=g.Oa;this.D=NaN;this.X=(0,g.z)(this.tR,this);this.B=g.Oa},fJa=function(a){a.B=a.P.OG(a.N,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Oa;
this.Nt(b)},a),(0,g.z)(function(b){this.B=g.Oa;
this.hg(b)},a))},gJa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.ba;MHa()&&(b.env_useStageMdx=1);return g.Gd(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.B=g.Do((0,g.z)(this.jn,this,null),150)},E7=function(a,b,c,d){g.O.call(this);
this.B=a;this.K=b||"233637DE";this.G=c||"cl";this.P=d||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.vO,this)},hJa=function(a,b){return b?g.jb(a.C,function(c){return g6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},LIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.F||!!a.C.length||!!a.u},H7=function(a,b,c){b!=a.u&&(g.ag(a.u),(a.u=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.u):a.V("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.DE,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.jn(null)):a.V("yt-remote-cast2-session-change",null))},iJa=function(a){var b=a.B.NG(),c=a.u&&a.u.u;
a=g.Pc(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=hJa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},oJa=function(a,b,c,d,e,f,h){jJa()?kJa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?lJa(a,c):(window.__onGCastApiAvailable=function(l,m){l?lJa(a,c):(K7("Failed to load cast API: "+m),L7(!1),J7(!1),g.vt("yt-remote-cast-available"),g.vt("yt-remote-cast-receiver"),mJa(),c(!1))},d?g.Po("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?THa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(SHa(),s6(nJa.map(QHa))))):I7("Cannot initialize because not running Chrome")},mJa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Ja("yt.mdx.remote.cloudview.instance_",null,void 0);pJa(!1);g.Lo(N7);N7.length=0},O7=function(){return!!g.ut("yt-remote-cast-installed")},qJa=function(){var a=g.ut("yt-remote-cast-receiver");
return a?a.friendlyName:null},rJa=function(){I7("clearCurrentReceiver");
g.vt("yt-remote-cast-receiver")},sJa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.Ko("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},jJa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.rB||a},tJa=function(a,b){M7().init(a,b)},kJa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.tt("yt-remote-cast-available",f);d6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.tt("yt-remote-cast-receiver",f);d6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.tt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+h6(f));
f||g.vt("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",f)}),g.Ja("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Na("yt.mdx.remote.cloudview.instance_")},lJa=function(a,b){L7(!0);
J7(!1);tJa(a,function(c){c?(pJa(!0),g.Mo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.vt("yt-remote-cast-available"),g.vt("yt-remote-cast-receiver"),mJa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.tt("yt-remote-cast-installed",a)},P7=function(){return!!g.Na("yt.mdx.remote.cloudview.apiReady_")},pJa=function(a){I7("setApiReady_ "+a);
g.Ja("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ja("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.K=0;this.u=null;this.hasNext=this.ii=!1;this.N=this.P=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.ii=!1;a.hasNext=!1;a.K=0;a.G=g.A();a.F=0;a.B=0;a.P=0;a.N=0;a.D=NaN;a.C=!1},U7=function(a){return a.Jb()?(g.A()-a.G)/1E3:0},V7=function(a,b){a.K=b;
a.G=g.A()},W7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.G)/1E3+a.K;
case -1E3:return 0}return a.K},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.u);b.hasPrevious=a.ii;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.G;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.P;b.loadedTime=a.N;b.liveIngestionTime=a.D;return b},$7=function(a,b){g.O.call(this);
this.Ha=0;this.C=a;this.F=[];this.D=new GIa;this.B=this.u=null;this.P=(0,g.z)(this.IM,this);this.G=(0,g.z)(this.Np,this);this.K=(0,g.z)(this.HM,this);this.N=(0,g.z)(this.QM,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.sz,this),uJa(this))):c=3;0!=c&&(b?this.sz(c):g.Do((0,g.z)(function(){this.sz(c)},this),0));
var d=sJa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},a8=function(a){return new S7(a.C.getPlayerContextData())},uJa=function(a){g.Fb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Va(this.rO,b),this))},a)},vJa=function(a){g.Fb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a){return 1==a.getState()},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){vJa(a);
a.C.setPlayerContextData(Y7(b));uJa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.P),a.B.removeMediaListener(a.G),a.Np(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.P),a.B.addMediaListener(a.G),a.B.media.length&&a.Np(a.B.media[0]))},wJa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());d8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.cd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.cd("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.O.call(this);
this.F=NaN;this.X=!1;this.P=this.K=this.N=this.W=NaN;this.Y=[];this.D=this.G=this.C=this.Cb=this.u=null;this.ea=a;this.Y.push(g.ap(window,"beforeunload",(0,g.z)(this.QI,this)));this.B=[];this.Cb=new S7;this.ba=b.id;this.u=xJa(this,c);this.u.subscribe("handlerOpened",this.MM,this);this.u.subscribe("handlerClosed",this.JM,this);this.u.subscribe("handlerError",this.KM,this);this.u.subscribe("handlerMessage",this.LM,this);KIa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Cb.videoId;
g.wt()&&g.tt("yt-remote-session-video-id",d)},this)},i8=function(a){j7("conn",a)},xJa=function(a,b){return new c7(g7(a.ea,"/bc"),b,!1,function(){return a.KG()})},j8=function(a,b){a.V("proxyStateChange",b)},yJa=function(a){a.F=g.Do((0,g.z)(function(){i8("Connecting timeout");
this.Nm(1)},a),2E4)},k8=function(a){g.Fo(a.F);
a.F=NaN},l8=function(a){g.Fo(a.W);
a.W=NaN},zJa=function(a){m8(a);
a.N=g.Do((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Fo(a.N);
a.N=NaN},BJa=function(a,b){b&&(k8(a),l8(a));
var c=e7(a.u)&&isNaN(a.F);b==c?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.zB()&&a.Cb.reset(),j8(a,1),n8(a,"getNowPlaying"),AJa(a)):a.Nm(1)},CJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Cb.videoId&&(g.Wb(b.params)?a.Cb.u=null:a.Cb.u=b.params,a.V("remotePlayerChange"))},DJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Cb.listId=b.params.listId||a.Cb.listId;X7(a.Cb,c,d);a.V("remoteQueueChange")},FJa=function(a,b){b.params=b.params||{};
DJa(a,b);EJa(a,b);a.V("autoplayDismissed")},EJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.Cb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Cb.playerState&&(c=-1E3);a.Cb.playerState=c;c=Number(b.params.loadedTime);a.Cb.N=isNaN(c)?0:c;c=Number(b.params.duration);a.Cb.P=isNaN(c)?0:c;c=a.Cb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Cb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Cb.playerState?zJa(a):m8(a);a.V("remotePlayerChange")},GJa=function(a,b){if(-1E3!=
a.Cb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Cb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.Cb,isNaN(c)?0:c);a.V("remotePlayerChange")}},HJa=function(a,b){var c="true"==b.params.muted;
a.Cb.volume=parseInt(b.params.volume,10);a.Cb.muted=c;a.V("remotePlayerChange")},IJa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},JJa=function(a,b){var c="true"==b.params.hasNext;
a.Cb.ii="true"==b.params.hasPrevious;a.Cb.hasNext=c;a.V("previousNextChange")},AJa=function(a){g.Fo(a.P);
a.P=g.Do((0,g.z)(a.Nm,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Cj(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){n7.call(this,"ScreenServiceProxy");
this.cf=a;this.u=[];this.u.push(this.cf.$_s("screenChange",(0,g.z)(this.oR,this)));this.u.push(this.cf.$_s("onlineScreenChange",(0,g.z)(this.WN,this)))},OJa=function(a,b){b=g.K("MDX_CONFIG")||b;
EHa();p6();p8||(p8=new f7(b?b.loungeApiHost:void 0),MHa()&&(p8.u="/api/loungedev"));q8||(q8=g.Na("yt.mdx.remote.deferredProxies_")||[],g.Ja("yt.mdx.remote.deferredProxies_",q8,void 0));KJa();var c=r8();if(!c){var d=new w7(p8);g.Ja("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);oJa(a,d,function(m){m?s8()&&R7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){d6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.Na("yt.mdx.remote.initialized_")&&(g.Ja("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Cj(b)),u8.push(g.Ko("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),u8.push(g.Ko("yt-remote-cast2-receiver-selected",function(){v8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.Ko("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.Ko("yt-remote-cast2-session-change",LJa)),u8.push(g.Ko("yt-remote-connection-change",function(m){m?R7(s8(),"YouTube TV"):w8()||(R7(null,null),rJa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.so("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.Cj(e)),MJa(e),c.start(),s8()||NJa())},QJa=function(){var a=PJa();
O7()&&g.ut("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},PJa=function(){var a=r8().cf.$_gos();
var b=y8();b&&z8()&&(k6(a,b)||a.push(b));return DHa(a)},A8=function(){var a=RJa();
!a&&O7()&&qJa()&&(a={key:"cast-selector-receiver",name:qJa()});return a},RJa=function(){var a=PJa(),b=y8();
b||(b=w8());return g.jb(a,function(c){return b&&g6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Yf();return l6(b,a)},LJa=function(a){t8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=y8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){j7("remote",a)},r8=function(){if(!F8){var a=g.Na("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Na("yt.mdx.remote.currentScreenId_")},SJa=function(a){g.Ja("yt.mdx.remote.currentScreenId_",a,void 0)},TJa=function(){return g.Na("yt.mdx.remote.connectData_")},v8=function(a){g.Ja("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Na("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||SJa("");g.Ja("yt.mdx.remote.connection_",a,void 0);q8&&(g.Fb(q8,function(c){c(a)}),q8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},w8=function(){var a=g.wt();
if(!a)return null;var b=r8();if(!b)return null;b=b.Yf();return l6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{SJa(a.id);var c=new h8(p8,a,x8());c.connect(b,TJa());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},NJa=function(){var a=w8();
a?(t8("Resume connection to: "+h6(a)),C8(a,0)):(q6(),rJa(),t8("Skipping connecting because no session screen found."))},KJa=function(){var a=x8();
if(g.Wb(a)){a=o6();var b=g.ut("yt-remote-session-name")||"",c=g.ut("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ja("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Na("yt.mdx.remote.channelParams_")||{}},MJa=function(a){a?(g.tt("yt-remote-session-app",a.app),g.tt("yt-remote-session-name",a.name)):(g.vt("yt-remote-session-app"),g.vt("yt-remote-session-name"));
g.Ja("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.B.call(this);
var d=this;this.B=a;this.J=b;this.ub=c;this.events=new g.nR(this);this.W=this.events.R(this.J,"onVolumeChange",function(e){UJa(d,e)});
this.F=!1;this.suggestion=null;this.G=new g.xL(64);this.u=new g.F(this.RF,500,this);this.C=new g.F(this.SF,1E3,this);this.P=new u6(this.SQ,0,this);this.D={};this.N=new g.F(this.vG,1E3,this);this.K=new v6(this.seekTo,1E3,this);this.X=g.Oa;g.C(this,this.events);this.events.R(b,"onCaptionsTrackListChanged",this.AN);this.events.R(b,"captionschanged",this.FM);this.events.R(b,"captionssettingschanged",this.VF);this.events.R(b,"videoplayerreset",this.Ot);this.events.R(b,"mdxautoplaycancel",function(){d.ub.UA()});
a=this.ub;a.la();a.subscribe("proxyStateChange",this.yE,this);a.subscribe("remotePlayerChange",this.Sp,this);a.subscribe("remoteQueueChange",this.Ot,this);a.subscribe("previousNextChange",this.vE,this);a.subscribe("nowAutoplaying",this.qE,this);a.subscribe("autoplayDismissed",this.SD,this);g.C(this,this.u);g.C(this,this.C);g.C(this,this.P);g.C(this,this.N);g.C(this,this.K);this.VF();this.Ot();this.Sp()},UJa=function(a,b){if(J8(a)){a.ub.unsubscribe("remotePlayerChange",a.Sp,a);
var c=Math.round(b.volume),d=!!b.muted,e=a8(a.ub);if(c!==e.volume||d!==e.muted)a.ub.setVolume(c,d),a.N.start();a.ub.subscribe("remotePlayerChange",a.Sp,a)}},VJa=function(a){a.Hc(0);
a.u.stop();a.Od(new g.xL(64))},K8=function(a,b){if(J8(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.bc(c,b));a.ub.LG(a.J.getVideoData(1).videoId,c);a.D=a8(a.ub).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.ub.playVideo(c.videoId,b,d,e,c.playerParams,c.Ag,qHa(c));a.Od(new g.xL(1))},WJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{YB:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return a8(a.ub).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{I:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{I:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{I:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"Connecting to your TV on web using a code will be going away soon"},{I:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{I:"button",ha:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"Learn more"},{I:"button",ha:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Z:"OK"}]}]}]});this.u=new g.gO(this,250);this.learnMoreButton=
this.ga("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ga("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.u);this.R(this.learnMoreButton,"click",this.B);this.R(this.okButton,"click",this.C)},N8=function(){g.V.call(this,{I:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{I:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{I:"div",L:"ytp-mdx-popup-title",Z:"You're signed out"},{I:"div",L:"ytp-mdx-popup-description",Z:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{I:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{I:"button",ha:["ytp-button","ytp-mdx-privacy-popup-cancel"],Z:"Cancel"},{I:"button",ha:["ytp-button","ytp-mdx-privacy-popup-confirm"],
Z:"Confirm"}]}]}]});this.u=new g.gO(this,250);this.cancelButton=this.ga("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ga("ytp-mdx-privacy-popup-confirm");g.C(this,this.u);this.R(this.cancelButton,"click",this.B);this.R(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,{I:"div",
L:"ytp-remote",S:[{I:"div",L:"ytp-remote-display-status",S:[{I:"div",L:"ytp-remote-display-status-icon",S:[g.FN()]},{I:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.gO(this,250);g.C(this,this.u);this.R(a,"presentingplayerstatechange",this.B);XJa(this,g.sJ(a))},XJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.qK("Error on $RECEIVER_NAME",c):b.Jb()||g.U(b,4)?g.qK("Playing on $RECEIVER_NAME",c):g.qK("Connected to $RECEIVER_NAME",c);a.xa("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.ZZ.call(this,"Play on",0,a,b);
this.J=a;this.Ik={};this.R(a,"onMdxReceiversChange",this.D);this.R(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.AS.call(this,a);
this.lh={key:j6(),name:"This computer"};this.Th=null;this.subscriptions=[];this.by=this.ub=null;this.Ik=[this.lh];this.bk=this.lh;this.Ac=new g.xL(64);this.uC=0;this.pe=-1;this.ln=null;this.Up=this.Us=!1;this.gm=this.Jn=null;if(!g.sC(this.player.T())){a=this.player;var b=g.TW(a);b&&(b=b.Cl())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.vP(a,b.element,4);this.Jn=new N8;g.C(this,this.Jn);g.vP(a,this.Jn.element,4);g.Q(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.Q(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.ln=new M8,g.C(this,this.ln),g.vP(a,this.ln.element,4));this.Up=!!w8();this.Us=!!g.ut("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.gm&&(a.player.removeEventListener("presentingplayerstatechange",a.gm),a.gm=null)},YJa=function(a,b,c){a.Ac=c;
a.player.V("presentingplayerstatechange",new g.CJ(c,b))},ZJa=function(a,b,c){var d=!1;
1===b?d=!a.Up:2===b&&(d=!a.Us);d&&g.EJ(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.bk.key)if(b.key===a.lh.key)B8();
else{if(a.ln&&!a.Us&&b!==a.lh&&"cast-selector-receiver"!==b.key&&g.CC(a.player.T()))$Ja(a);else{var c;(c=!g.Q(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Up||!a.Jn);(c?0:g.CC(a.player.T())||g.GC(a.player.T()))&&aKa(a)}a.bk=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ka(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ag,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=qHa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Cj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?d6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Yf(),(c=l6(c,b.key))&&C8(c,1))}},aKa=function(a){g.sJ(a.player).Jb()?a.player.pauseVideo():(a.gm=function(b){ZJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.gm));
a.Jn&&a.Jn.tc();z8()||(G8=!0)},$Ja=function(a){g.sJ(a.player).Jb()?a.player.pauseVideo():(a.gm=function(b){ZJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.gm));
a.ln&&a.ln.tc();z8()||(G8=!0)},cIa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},K6={"'":"\\'"},bKa={},zHa={kS:"atp",r1:"ska",m0:"que",wZ:"mus",q1:"sus",PV:"dsp",E0:"seq",bZ:"mic",NU:"dpa"},r6,n6="",RHa=NHa("loadCastFramework")||NHa("loadCastApplicationFramework"),nJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ya(u6,g.B);g.k=u6.prototype;g.k.MI=function(a){this.D=arguments;this.u=!1;this.Va?this.C=g.A()+this.df:this.Va=g.Rm(this.F,this.df)};
g.k.stop=function(){this.Va&&(g.v.clearTimeout(this.Va),this.Va=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.G.apply(null,this.D)))};
g.k.aa=function(){this.stop();u6.od.aa.call(this)};
g.k.NI=function(){this.C?(this.Va=g.Rm(this.F,this.C-g.A()),this.C=null):(this.Va=null,this.B?this.u=!0:(this.u=!1,this.G.apply(null,this.D)))};g.u(v6,g.B);g.k=v6.prototype;g.k.LC=function(a){this.C=arguments;this.Va||this.B?this.u=!0:w6(this)};
g.k.stop=function(){this.Va&&(g.v.clearTimeout(this.Va),this.Va=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Va||(this.u=!1,w6(this))};
g.k.aa=function(){g.B.prototype.aa.call(this);this.stop()};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var A6=new g.fm;g.u(UHa,g.Il);C6.prototype.u=null;C6.prototype.getOptions=function(){var a;(a=this.u)||(a={},WHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Ya(VHa,C6);T8=new VHa;g.k=D6.prototype;g.k.Fl=null;g.k.Eh=!1;g.k.fo=null;g.k.pz=null;g.k.On=null;g.k.Xn=null;g.k.Uj=null;g.k.Jk=null;g.k.hm=null;g.k.ee=null;g.k.Iq=0;g.k.Jh=null;g.k.Fu=null;g.k.kk=null;g.k.ep=-1;g.k.IF=!0;g.k.kl=!1;g.k.Cw=0;g.k.Xt=null;var aIa={},G6={};g.k=D6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.WP=function(a){a=a.target;var b=this.Xt;b&&3==P6(a)?b.LC():this.HG(a)};
g.k.HG=function(a){try{if(a==this.ee)a:{var b=P6(this.ee),c=this.ee.G,d=this.ee.getStatus();if(g.xe&&!g.Zd(10)||g.ze&&!g.Yd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.og&&!R6(this.ee))break a;this.kl||4!=b||7==c||(8==c||0>=d?this.u.uh(3):this.u.uh(2));L6(this);var e=this.ee.getStatus();this.ep=e;var f=R6(this.ee);(this.Eh=200==e)?(4==b&&I6(this),this.G?(bIa(this,b,f),g.og&&this.Eh&&3==b&&(this.D.wa(this.C,"tick",this.RP),this.C.start())):H6(this,f),this.Eh&&!this.kl&&(4==b?this.u.ls(this):(this.Eh=
!1,F6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kk=3,B6(13)):(this.kk=0,B6(14)),I6(this),J6(this))}}catch(h){this.ee&&R6(this.ee)}finally{}};
g.k.RP=function(){var a=P6(this.ee),b=R6(this.ee);this.Iq<b.length&&(L6(this),bIa(this,a,b),this.Eh&&4!=a&&F6(this))};
g.k.kP=function(a){z6((0,g.z)(this.jP,this,a),0)};
g.k.jP=function(a){this.kl||(L6(this),H6(this,a),F6(this))};
g.k.HE=function(a){z6((0,g.z)(this.iP,this,a),0)};
g.k.iP=function(a){this.kl||(I6(this),this.Eh=a,this.u.ls(this),this.u.uh(4))};
g.k.cancel=function(){this.kl=!0;I6(this)};
g.k.wP=function(){this.fo=null;var a=g.A();0<=a-this.pz?(2!=this.Xn&&this.u.uh(3),I6(this),this.kk=2,B6(18),J6(this)):eIa(this,this.pz-a)};
g.k.getLastError=function(){return this.kk};g.Ya(N6,g.fm);var lIa=/^https?$/i,cKa=["POST","PUT"];g.k=N6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.N+"; newUri="+a);b=b?b.toUpperCase():"GET";this.N=a;this.D="";this.G=0;this.ra=b;this.ea=!1;this.C=!0;this.u=this.ba?XHa(this.ba):XHa(T8);this.Y=this.ba?this.ba.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.wE,this);try{c6(Q6(this,"Opening Xhr")),this.ia=!0,this.u.open(b,String(a),!0),this.ia=!1}catch(f){c6(Q6(this,"Error opening Xhr: "+f.message));kIa(this,f);return}a=
c||"";var e=this.headers.clone();d&&vHa(d,function(f,h){e.set(h,f)});
d=g.jb(e.xg(),iIa);c=g.v.FormData&&a instanceof g.v.FormData;!g.nb(cKa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.Aa&&(this.u.responseType=this.Aa);"withCredentials"in this.u&&this.u.withCredentials!==this.da&&(this.u.withCredentials=this.da);try{nIa(this),0<this.K&&(this.X=hIa(this.u),c6(Q6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.X)),this.X?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.KB,this)):this.W=g.Rm(this.KB,this.K,this)),c6(Q6(this,"Sending request")),this.P=!0,this.u.send(a),this.P=!1}catch(f){c6(Q6(this,"Send error: "+f.message)),kIa(this,f)}};
g.k.KB=function(){"undefined"!=typeof g.p1&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.G=8,Q6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.C&&(Q6(this,"Aborting"),this.C=!1,this.F=!0,this.u.abort(),this.F=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),O6(this))};
g.k.aa=function(){this.u&&(this.C&&(this.C=!1,this.F=!0,this.u.abort(),this.F=!1),O6(this,!0));N6.od.aa.call(this)};
g.k.wE=function(){this.la()||(this.ia||this.P||this.F?mIa(this):this.uO())};
g.k.uO=function(){mIa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<P6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=oIa.prototype;g.k.Aw=null;g.k.Qf=null;g.k.Yt=!1;g.k.JB=null;g.k.Ir=null;g.k.kx=null;g.k.Bw=null;g.k.Ha=null;g.k.hj=-1;g.k.bp=null;g.k.xo=null;g.k.connect=function(a){this.Bw=a;a=S6(this.u,null,this.Bw);B6(3);this.JB=g.A();var b=this.u.K;null!=b?(this.bp=b[0],(this.xo=b[1])?(this.Ha=1,pIa(this)):(this.Ha=2,U6(this))):(a6(a,"MODE","init"),this.Qf=new D6(this,void 0,void 0,void 0),this.Qf.Fl=this.Aw,E6(this.Qf,a,!1,null,!0),this.Ha=0)};
g.k.LH=function(a){if(a)this.Ha=2,U6(this);else{B6(4);var b=this.u;b.hi=b.Zj.hj;a7(b,9)}a&&this.uh(2)};
g.k.Kv=function(a){return this.u.Kv(a)};
g.k.abort=function(){this.Qf&&(this.Qf.cancel(),this.Qf=null);this.hj=-1};
g.k.IB=function(){return!1};
g.k.zE=function(a,b){this.hj=a.ep;if(0==this.Ha)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.hi=this.hj;a7(c,2);return}this.bp=c[0];this.xo=c[1]}else c=this.u,c.hi=this.hj,a7(c,2);else if(2==this.Ha)if(this.Yt)B6(7),this.kx=g.A();else if("11111"==b){if(B6(6),this.Yt=!0,this.Ir=g.A(),c=this.Ir-this.JB,!g.xe||g.Zd(10)||500>c)this.hj=200,this.Qf.cancel(),B6(12),T6(this.u,this,!0)}else B6(8),this.Ir=this.kx=g.A(),this.Yt=!1};
g.k.ls=function(){this.hj=this.Qf.ep;if(this.Qf.Eh)0==this.Ha?this.xo?(this.Ha=1,pIa(this)):(this.Ha=2,U6(this)):2==this.Ha&&((!g.xe||g.Zd(10)?!this.Yt:200>this.kx-this.Ir)?(B6(11),T6(this.u,this,!1)):(B6(12),T6(this.u,this,!0)));else{0==this.Ha?B6(9):2==this.Ha&&B6(10);var a=this.u;this.Qf.getLastError();a.hi=this.hj;a7(a,2)}};
g.k.qq=function(){return this.u.qq()};
g.k.isActive=function(){return this.u.isActive()};
g.k.uh=function(a){this.u.uh(a)};g.k=V6.prototype;g.k.Xm=null;g.k.No=null;g.k.Hf=null;g.k.zd=null;g.k.zw=null;g.k.Kr=null;g.k.nA=null;g.k.ks=null;g.k.Lp=0;g.k.UL=0;g.k.af=null;g.k.dk=null;g.k.Ui=null;g.k.rl=null;g.k.Zj=null;g.k.Cu=null;g.k.hn=-1;g.k.tC=-1;g.k.hi=-1;g.k.Sm=0;g.k.Dm=0;g.k.ll=8;g.Ya(sIa,g.Il);g.Ya(tIa,g.Il);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){B6(0);this.zw=b;this.No=c||{};d&&void 0!==e&&(this.No.OSID=d,this.No.OAID=e);this.F?(z6((0,g.z)(this.DA,this,a),100),xIa(this)):this.DA(a)};
g.k.DA=function(a){this.Zj=new oIa(this);this.Zj.Aw=this.Xm;this.Zj.B=this.D;this.Zj.connect(a)};
g.k.IB=function(){return 0==this.Ha};
g.k.getState=function(){return this.Ha};
g.k.GE=function(a){this.dk=null;BIa(this,a)};
g.k.FE=function(){this.Ui=null;this.zd=new D6(this,this.B,"rpc",this.G);this.zd.Fl=this.Xm;this.zd.Cw=0;var a=this.nA.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.B);Z5(a,"CI",this.Cu?"0":"1");Z5(a,"AID",this.hn);W6(this,a);if(!g.xe||g.Zd(10))Z5(a,"TYPE","xmlhttp"),E6(this.zd,a,!0,this.ks,!1);else{Z5(a,"TYPE","html");var b=this.zd,c=!!this.ks;b.Xn=3;b.Uj=$5(a.clone());dIa(b,c)}};
g.k.zE=function(a,b){if(0!=this.Ha&&(this.zd==a||this.Hf==a))if(this.hi=a.ep,this.Hf==a&&3==this.Ha)if(7<this.ll){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Ui){if(this.zd)if(this.zd.On+3E3<this.Hf.On)Y6(this),this.zd.cancel(),this.zd=null;else break a;$6(this);B6(19)}}else this.tC=c[1],0<this.tC-this.hn&&37500>c[2]&&this.Cu&&0==this.Dm&&!this.rl&&(this.rl=z6((0,g.z)(this.zM,this),6E3));else a7(this,11)}else b!=bKa.BU.u&&a7(this,11);else if(this.zd==
a&&Y6(this),!g.rc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.hn=e[0];e=e[1];2==this.Ha?"c"==e[0]?(this.B=e[1],this.ks=e[2],e=e[3],null!=e?this.ll=e:this.ll=6,this.Ha=3,this.af&&this.af.zA(),this.nA=S6(this,this.qq()?this.ks:null,this.zw),CIa(this)):"stop"==e[0]&&a7(this,7):3==this.Ha&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.af&&this.af.yA(e),this.Dm=0)}}};
g.k.zM=function(){null!=this.rl&&(this.rl=null,this.zd.cancel(),this.zd=null,$6(this),B6(20))};
g.k.ls=function(a){if(this.zd==a){Y6(this);this.zd=null;var b=2}else if(this.Hf==a)this.Hf=null,b=1;else return;this.hi=a.ep;if(0!=this.Ha)if(a.Eh)1==b?(b=A6,b.dispatchEvent(new sIa(b,a.hm?a.hm.length:0,g.A()-a.On,this.Sm)),X6(this),this.C.length=0):CIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.hi)){if(d=1==b)this.Hf||this.dk||1==this.Ha||2<=this.Sm?d=!1:(this.dk=z6((0,g.z)(this.GE,this,a),DIa(this,this.Sm)),this.Sm++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.kI=function(a){if(!g.nb(arguments,this.Ha))throw Error("Unexpected channel state: "+this.Ha);};
g.k.FQ=function(a){a?B6(2):(B6(1),EIa(this,8))};
g.k.Kv=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N6;a.da=!1;return a};
g.k.isActive=function(){return!!this.af&&this.af.isActive(this)};
g.k.uh=function(a){var b=A6;b.dispatchEvent(new tIa(b,a))};
g.k.qq=function(){return!(!g.xe||g.Zd(10))};
g.k=FIa.prototype;g.k.zA=function(){};
g.k.yA=function(){};
g.k.xA=function(){};
g.k.yv=function(){};
g.k.kB=function(){return{}};
g.k.isActive=function(){return!0};g.k=GIa.prototype;g.k.isEmpty=function(){return g.ob(this.u)&&g.ob(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.nb(this.u,a)||g.nb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.FBa)(b,a);0<=c?(g.qb(b,c),b=!0):b=!1;return b||g.rb(this.B,a)};
g.k.rf=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Ya(b7,g.B);g.k=b7.prototype;g.k.dP=function(){this.df=Math.min(3E5,2*this.df);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.df+15E3*Math.random();this.u.Gb(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.df=5E3};g.Ya(c7,FIa);g.k=c7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.Ck=function(a){return this.C.Gl(a)};
g.k.V=function(a,b){return this.C.V.apply(this.C,arguments)};
g.k.dispose=function(){this.Qd||(this.Qd=!0,g.ag(this.C),JIa(this),g.ag(this.B),this.B=null,this.X=function(){return""})};
g.k.la=function(){return this.Qd};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.getState()){this.N="";this.B.stop();this.F=a||null;this.D=b||0;a=this.W+"/test";b=this.W+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Y),e=this.u;e&&(e.af=null);d.af=this;this.u=d;d7(this);e?(3!=e.getState()&&0==zIa(e)||e.getState(),this.u.connect(a,b,this.G,e.B,e.hn)):c?this.u.connect(a,b,this.G,c.sessionId,c.arrayId):this.u.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.B.isActive()||2==(this.u?this.u.getState():0)?this.K.push(c):e7(this)&&(d7(this),yIa(this.u,c))};
g.k.zA=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)yIa(this.u,a[b])}this.V("handlerOpened")};
g.k.xA=function(a){var b=2==a&&401==this.u.hi;4==a||b||this.B.start();this.V("handlerError",a)};
g.k.yv=function(a){if(!this.B.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.kB=function(){var a={v:2};this.N&&(a.gsessionid=this.N);0!=this.D&&(a.ui=""+this.D);0!=this.P&&(a.ui=""+this.P);this.F&&g.bc(a,this.F);return a};
g.k.yA=function(a){"S"==a[0]?this.N=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),wIa(this.u)):this.V("handlerMessage",new HIa(a[0],a[1]))};
g.k.iQ=function(){this.B.isActive();0==zIa(this.u)&&this.connect(this.F,this.D)};f7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.F=function(a){a(Error("request timed out"))};var RIa=g.A(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Ya(n7,g.O);n7.prototype.Yf=function(){return this.screens};
n7.prototype.contains=function(a){return!!k6(this.screens,a)};
n7.prototype.get=function(a){return a?l6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.u(o7,g.O);g.k=o7.prototype;g.k.start=function(){!this.u&&isNaN(this.Va)&&this.MG()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Va)||(g.Fo(this.Va),this.Va=NaN)};
g.k.aa=function(){this.stop();g.O.prototype.aa.call(this)};
g.k.MG=function(){this.Va=NaN;this.u=g.mq(g7(this.G,"/pairing/get_screen"),{method:"POST",dc:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.mR,this),onError:(0,g.z)(this.lR,this),kg:(0,g.z)(this.nR,this)})};
g.k.mR=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.V("pairingComplete",new f6(c))};
g.k.lR=function(a){this.u=null;a.status&&404==a.status?this.B>=dKa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=dKa[this.B],this.Va=g.Do((0,g.z)(this.MG,this),a),this.B++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.nR=function(){this.u=null;this.V("pairingFailed",Error("Server not responding"))};
var dKa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ya(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.V("screenChange");!g.ut("yt-remote-lounge-token-expiration")&&VIa(this);g.Fo(this.u);this.u=g.Do((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);SIa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||VIa(this)};
g.k.remove=function(a,b){var c=p7(this);UIa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Au=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.aa=function(){g.Fo(this.u);q7.od.aa.call(this)};
g.k.XI=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.k.WI=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.u(t7,g.O);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.ut("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?v7(this):(this.D=g.A()+3E5,g.tt("yt-remote-fast-check-period",this.D),this.ry())};
g.k.isEmpty=function(){return g.Wb(this.u)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.G(),b=g.Jb(this.u,function(c,d){return c&&!!l6(a,d)},this);
u7(this,b)};
g.k.aa=function(){g.Fo(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.O.prototype.aa.call(this)};
g.k.ry=function(){g.Fo(this.C);this.C=NaN;this.B&&this.B.abort();var a=YIa(this);if(b6(a)){var b=g7(this.F,"/pairing/get_screen_availability");this.B=h7(this.F,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.OO,this,a),(0,g.z)(this.NO,this))}else u7(this,{}),v7(this)};
g.k.OO=function(a,b){this.B=null;var c=g.Qb(YIa(this));if(g.Db(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.cd("Changing Screen set during request."),this.ry()};
g.k.NO=function(a){this.cd("Screen availability failed: "+a);this.B=null;v7(this)};
g.k.cd=function(a){j7("OnlineScreenService",a)};g.Ya(w7,n7);g.k=w7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.V("screenChange"),this.u.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.Au=function(a,b,c,d){this.B.contains(a)?this.B.Au(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.k.Yf=function(a){return a?this.screens:g.tb(this.screens,g.Je(this.C,function(b){return!this.contains(b)},this))};
g.k.NG=function(){return g.Je(this.Yf(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.OG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.ag(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.ag(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.pR=function(a,b,c,d){g.mq(g7(this.F,"/pairing/get_screen"),{method:"POST",dc:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new f6(f.screen||{});if(!h.name||bJa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);bJa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
kg:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.aa=function(){g.ag(this.B);g.ag(this.u);w7.od.aa.call(this)};
g.k.eJ=function(){cJa(this);this.V("screenChange");this.u.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Ya(z7,g.O);g.k=z7.prototype;g.k.getScreen=function(){return this.K};
g.k.Nt=function(a){this.K=a;this.V("sessionScreen",this.K)};
g.k.hg=function(a){this.la()||(a&&A7(this,""+a),this.K=null,this.V("sessionScreen",null))};
g.k.info=function(a){j7(this.Y,a)};
g.k.QG=function(){return null};
g.k.Cy=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.aa=function(){this.Cy("");z7.od.aa.call(this)};g.u(B7,z7);g.k=B7.prototype;g.k.By=function(a){if(this.B){if(this.B==a)return;A7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);eJa(this)};
g.k.jn=function(a){this.info("launchWithParams no-op for Cast: "+g.Cj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.hg()},this),(0,g.z)(function(){this.hg(Error("Failed to stop receiver app."))},this)):this.hg(Error("Stopping cast device witout session."))};
g.k.Cy=function(){};
g.k.aa=function(){this.info("disposeInternal");g.Fo(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;z7.prototype.aa.call(this)};
g.k.DP=function(a,b){if(!this.la())if(b){var c=x6(b);if(g.Sa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Cj(c));switch(d){case "mdxSessionStatus":dJa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.BB=function(a,b,c,d){aJa(this.P,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Do((0,g.z)(this.BB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.QG=function(){return this.B};
g.k.qR=function(a){this.la()||a||(A7(this,"Cast session died."),this.hg())};g.u(C7,z7);g.k=C7.prototype;g.k.By=function(a){this.C=a;this.C.addUpdateListener(this.X)};
g.k.jn=function(a){this.W=a;this.F()};
g.k.stop=function(){this.B();this.B=g.Oa;g.Fo(this.D);this.C?this.C.stop((0,g.z)(this.hg,this,null),(0,g.z)(this.hg,this,"Failed to stop DIAL device.")):this.hg()};
g.k.aa=function(){this.B();this.B=g.Oa;g.Fo(this.D);this.C&&this.C.removeUpdateListener(this.X);this.C=null;z7.prototype.aa.call(this)};
g.k.tR=function(a){this.la()||a||(A7(this,"DIAL session died."),this.B(),this.B=g.Oa,this.hg())};
g.k.Nw=function(a){this.N=j6();if(this.W){var b=new chrome.cast.DialLaunchResponse(!0,gJa(this));a(b);fJa(this)}else this.F=(0,g.z)(function(){g.Fo(this.D);this.F=g.Oa;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,gJa(this));a(c);fJa(this)},this),this.D=g.Do((0,g.z)(function(){this.F()},this),100)};
g.k.vJ=function(a,b,c){aJa(this.P,this.G.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Nt(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Nw(b,c)},this),(0,g.z)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.Nw(b,c)},this))};g.u(D7,z7);D7.prototype.stop=function(){this.hg()};
D7.prototype.By=function(){};
D7.prototype.jn=function(){g.Fo(this.B);this.B=NaN;var a=l6(this.P.Yf(),this.u.label);a?this.Nt(a):this.hg(Error("No such screen"))};
D7.prototype.aa=function(){g.Fo(this.B);this.B=NaN;z7.prototype.aa.call(this)};g.u(E7,g.O);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.P||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.yO,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.BE,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.YM,this);chrome.cast.initialize(c,(0,g.z)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.D),OIa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.PG,this)),this.C=iJa(this),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(h){this.cd("Failed to set initial custom receivers: "+g.Cj(h))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.z)(function(h){this.cd("Failed to initialize API: "+g.Cj(h));
b(!1)},this))};
g.k.nQ=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.u.u.friendlyName),H7(this,null)}if(a&&b){if(!this.u){c=l6(this.B.Yf(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=hJa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.Oa,(0,g.z)(function(e){this.cd("Failed to set initial custom receivers: "+g.Cj(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.B,d),!0)}this.u.Cy(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.oQ=function(a){this.la()?this.cd("Setting connection data on disposed cast v2"):this.u?this.u.jn(a):this.cd("Setting connection data without a session")};
g.k.sR=function(){this.la()?this.cd("Stopping session on disposed cast v2"):this.u?(this.u.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.BE,this),(0,g.z)(this.QO,this))};
g.k.aa=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.PG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=LIa,b=g.Na("yt.mdx.remote.debug.handlers_");g.rb(b||[],a);g.ag(this.u);g.O.prototype.aa.call(this)};
g.k.cd=function(a){j7("Controller",a)};
g.k.DE=function(a,b){this.u==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.vO=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.V("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.B,a,this.G));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.B,a));break;default:this.cd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.cd("Stopping receiver w/o session: "+a.friendlyName)}else this.cd("onReceiverAction_ called without receiver.")};
g.k.YM=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.cd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.cd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.cd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.B,b,this.G))}b=this.u;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.vJ,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Nw,b))};
g.k.BE=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.B,b),!0);else{this.cd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=l6(this.B.Yf(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ag(this.u),this.u=new B7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.DE,this,this.u)),this.u.jn(null));this.u.By(a)}}};
g.k.rR=function(){return this.u?this.u.QG():null};
g.k.QO=function(a){this.la()||(this.cd("Failed to estabilish a session: "+g.Cj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.yO=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.k.PG=function(){this.la()||(this.C=iJa(this),F7("Updating custom receivers: "+g.Cj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Oa,(0,g.z)(function(){this.cd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.oQ;E7.prototype.setConnectedScreenStatus=E7.prototype.nQ;E7.prototype.stopSession=E7.prototype.sR;E7.prototype.getCastSession=E7.prototype.rR;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.ii=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.G=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.P=a.duration,this.N=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Jb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.C?this.P+U7(this):this.P};
g.k.clone=function(){return new S7(Y7(this))};g.u($7,g.O);g.k=$7.prototype;g.k.getState=function(){return this.Ha};
g.k.play=function(){b8(this)?(this.u?this.u.play(null,g.Oa,g8(this,"play")):f8(this,"play"),e8(this,1,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){b8(this)?(this.u?this.u.pause(null,g.Oa,g8(this,"pause")):f8(this,"pause"),e8(this,2,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(b8(this)){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Jb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Oa,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.V("remotePlayerChange")}else c8(this,g.Va(this.seekTo,a))};
g.k.stop=function(){if(b8(this)){this.u?this.u.stop(null,g.Oa,g8(this,"stopVideo")):f8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);d8(this,a);this.V("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(b8(this)){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.cd("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.cd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Va(this.setVolume,a,b))};
g.k.LG=function(a,b){if(b8(this)){var c=a8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Cj(b.style),g.bc(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Va(this.LG,a,b))};
g.k.setAudioTrack=function(a,b){if(b8(this)){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Va(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Cj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.Tt=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Va(this.Tt,a,b))};
g.k.nextVideo=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Va(this.nextVideo,a,b))};
g.k.UA=function(){b8(this)?f8(this,"dismissAutoplay"):c8(this,this.UA)};
g.k.dispose=function(){if(3!=this.Ha){var a=this.Ha;this.Ha=3;this.V("proxyStateChange",a,this.Ha)}g.O.prototype.dispose.call(this)};
g.k.aa=function(){vJa(this);this.C=null;this.D.clear();Z7(this,null);g.O.prototype.aa.call(this)};
g.k.sz=function(a){if((a!=this.Ha||2==a)&&3!=this.Ha&&0!=a){var b=this.Ha;this.Ha=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.ob(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.rO=function(a,b){this.V(a,b)};
g.k.IM=function(a){if(!a)this.Np(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Np=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),wJa(this),this.V("remotePlayerChange")};
g.k.HM=function(a){a?(wJa(this),this.V("remotePlayerChange")):this.Np(null)};
g.k.Uy=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.QM=function(){var a=sJa();a&&Z7(this,a)};
g.k.cd=function(a){j7("CP",a)};g.u(h8,g.O);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Cb.listId=c);this.Cb.videoId=d;this.Cb.index=h||0;this.Cb.state=3;V7(this.Cb,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Cj(l));this.u.connect({method:"setPlaylist",
params:g.Cj(l)},a,HHa())}else i8("Connecting without params"),this.u.connect({},a,HHa());yJa(this)};
g.k.dispose=function(){this.la()||(this.V("beforeDispose"),j8(this,3));g.O.prototype.dispose.call(this)};
g.k.aa=function(){k8(this);m8(this);l8(this);g.Fo(this.K);this.K=NaN;g.Fo(this.P);this.P=NaN;this.C=null;g.bp(this.Y);this.Y.length=0;this.u.dispose();g.O.prototype.aa.call(this);this.D=this.G=this.B=this.Cb=this.u=null};
g.k.QI=function(){this.Nm(2)};
g.k.MM=function(){i8("Channel opened");this.X&&(this.X=!1,l8(this),this.W=g.Do((0,g.z)(function(){i8("Timing out waiting for a screen.");this.Nm(1)},this),15E3));
LHa(IIa(this.u),this.ba)};
g.k.JM=function(){i8("Channel closed");isNaN(this.F)?q6(!0):q6();this.dispose()};
g.k.KM=function(a){q6();isNaN(this.Wo())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.X=!0,i8("Channel error: "+a+" with reconnection in "+this.Wo()+" ms"),j8(this,2))};
g.k.LM=function(a){a.params?i8("Received: action="+a.action+", params="+g.Cj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.B=g.Pc(a,function(c){return new e6(c)});
a=!!g.jb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
BJa(this,a);break;case "loungeScreenDisconnected":g.sb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
BJa(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.jb(this.B,function(c){return b?c.id==b.id:!1})||rHa(this.B,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.sb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":DJa(this,a);break;case "nowPlaying":FJa(this,a);break;case "onStateChange":EJa(this,a);break;case "onAdStateChange":GJa(this,a);break;case "onVolumeChanged":HJa(this,a);break;case "onSubtitlesTrackChanged":CJa(this,a);break;case "nowAutoplaying":IJa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.V("autoplayModeChange",this.D);"DISABLED"==this.D&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":JJa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.eQ=function(){if(this.C){var a=this.C;this.C=null;this.Cb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.GI=function(){var a=3;this.la()||(a=0,isNaN(this.Wo())?e7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Nm=function(a){i8("Disconnecting with "+a);k8(this);this.V("beforeDisconnect",a);1==a&&q6();JIa(this.u,a);this.dispose()};
g.k.DI=function(){var a=this.Cb;this.C&&(a=this.Cb.clone(),X7(a,this.C,a.index));return Y7(a)};
g.k.pQ=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.Cb.videoId&&(this.C=b.videoId,g.Fo(this.K),this.K=g.Do((0,g.z)(this.eQ,this),5E3));var c=[];this.Cb.listId==b.listId&&this.Cb.videoId==b.videoId&&this.Cb.index==b.index||c.push("remoteQueueChange");this.Cb.playerState==b.playerState&&this.Cb.volume==b.volume&&this.Cb.muted==b.muted&&W7(this.Cb)==W7(b)&&g.Cj(this.Cb.u)==g.Cj(b.u)||c.push("remotePlayerChange");this.Cb.reset(a);g.Fb(c,function(d){this.V(d)},this)};
g.k.zB=function(){var a=this.u.G.id,b=g.jb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Wo=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.sI=function(){return this.D||"UNSUPPORTED"};
g.k.tI=function(){return this.G||""};
g.k.kR=function(){if(!isNaN(this.Wo())){var a=this.u.B;g.qn(a.u);a.start()}};
g.k.lQ=function(a,b){n8(this,a,b);AJa(this)};
g.k.KG=function(){var a=g.tq("SID","")||"",b=g.tq("SAPISID","")||"",c=g.tq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.pf(g.Ue(a),2);b=g.pf(g.Ue(b),2);c=g.pf(g.Ue(c),2);return g.pf(g.Ue(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Ck;h8.prototype.getProxyState=h8.prototype.GI;h8.prototype.disconnect=h8.prototype.Nm;h8.prototype.getPlayerContextData=h8.prototype.DI;h8.prototype.setPlayerContextData=h8.prototype.pQ;h8.prototype.getOtherConnectedRemoteId=h8.prototype.zB;h8.prototype.getReconnectTimeout=h8.prototype.Wo;h8.prototype.getAutoplayMode=h8.prototype.sI;h8.prototype.getAutoplayVideoId=h8.prototype.tI;h8.prototype.reconnect=h8.prototype.kR;
h8.prototype.sendMessage=h8.prototype.lQ;h8.prototype.getXsrfToken=h8.prototype.KG;g.u(o8,n7);g.k=o8.prototype;g.k.Yf=function(a){return this.cf.$_gs(a)};
g.k.contains=function(a){return!!this.cf.$_c(a)};
g.k.get=function(a){return this.cf.$_g(a)};
g.k.start=function(){this.cf.$_st()};
g.k.add=function(a,b,c){this.cf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.cf.$_r(a,b,c)};
g.k.Au=function(a,b,c,d){this.cf.$_un(a,b,c,d)};
g.k.aa=function(){for(var a=0,b=this.u.length;a<b;++a)this.cf.$_ubk(this.u[a]);this.u.length=0;this.cf=null;n7.prototype.aa.call(this)};
g.k.oR=function(){this.V("screenChange")};
g.k.WN=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.pR;w7.prototype.$_gsppc=w7.prototype.OG;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Au;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Yf;w7.prototype.$_gos=w7.prototype.NG;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Ck;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.B);g.k=I8.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.u.stop();this.C.stop();this.P.stop();this.X();var a=this.ub;a.unsubscribe("proxyStateChange",this.yE,this);a.unsubscribe("remotePlayerChange",this.Sp,this);a.unsubscribe("remoteQueueChange",this.Ot,this);a.unsubscribe("previousNextChange",this.vE,this);a.unsubscribe("nowAutoplaying",this.qE,this);a.unsubscribe("autoplayDismissed",this.SD,this);this.ub=this.B=null};
g.k.dD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ub.Ha)if(J8(this)){if(!a8(this.ub).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.ub).Jb()?this.ub.pause():this.ub.play();break;case "control_play":this.ub.play();break;case "control_pause":this.ub.pause();break;case "control_seek":this.K.LC(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.FM=function(a){this.P.MI(a)};
g.k.SQ=function(a){this.dD("control_subtitles_set_track",g.Wb(a)?null:a)};
g.k.VF=function(){var a=this.J.getOption("captions","track");g.Wb(a)||K8(this,a)};
g.k.Hc=function(a){this.B.Hc(a,this.J.getVideoData().lengthSeconds)};
g.k.AN=function(){g.Wb(this.D)||WJa(this,this.D);this.F=!1};
g.k.yE=function(a,b){this.C.stop();2===b&&this.SF()};
g.k.Sp=function(){if(J8(this)){this.u.stop();var a=a8(this.ub);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.pe=1;break;case 1082:case 1083:this.B.pe=0;break;default:this.B.pe=-1}switch(a.playerState){case 1081:case 1:this.Od(new g.xL(8));this.RF();break;case 1085:case 3:this.Od(new g.xL(9));break;case 1083:case 0:this.Od(new g.xL(2));this.K.stop();this.Hc(this.J.getVideoData().lengthSeconds);break;case 1084:this.Od(new g.xL(4));break;case 2:this.Od(new g.xL(4));this.Hc(W7(a));
break;case -1:this.Od(new g.xL(64));break;case -1E3:this.Od(new g.xL(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a8(this.ub).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,WJa(this,a));a=a8(this.ub);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.N.isActive()||this.vG()}else VJa(this)};
g.k.vE=function(){this.J.V("mdxpreviousnextchange")};
g.k.Ot=function(){J8(this)||VJa(this)};
g.k.qE=function(a){isNaN(a)||this.J.V("mdxnowautoplaying",a)};
g.k.SD=function(){this.J.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.ub.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.ub).playerState?L8(this,a):b&&this.ub.seekTo(a)};
g.k.vG=function(){var a=this;if(J8(this)){var b=a8(this.ub);this.events.Db(this.W);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.W=this.events.R(this.J,"onVolumeChange",function(c){UJa(a,c)})}};
g.k.RF=function(){this.u.stop();if(!this.ub.la()){var a=a8(this.ub);a.Jb()&&this.Od(new g.xL(8));this.Hc(W7(a));this.u.start()}};
g.k.SF=function(){this.C.stop();this.u.stop();var a=this.ub.C.getReconnectTimeout();2==this.ub.Ha&&!isNaN(a)&&this.C.start()};
g.k.Od=function(a){this.C.stop();var b=this.G;if(!g.CL(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&g.K0(this.J.app,c);this.G=a;YJa(this.B,b,a)}};g.u(M8,g.V);M8.prototype.tc=function(){this.u.show()};
M8.prototype.gb=function(){this.u.hide()};
M8.prototype.B=function(){g.OK("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){d6("mdx-manual-pairing-popup-ok");this.gb()};g.u(N8,g.V);N8.prototype.tc=function(){this.u.show()};
N8.prototype.gb=function(){this.u.hide()};
N8.prototype.B=function(){d6("mdx-privacy-popup-cancel");this.gb()};
N8.prototype.C=function(){d6("mdx-privacy-popup-confirm");this.gb()};g.u(O8,g.V);O8.prototype.B=function(a){XJa(this,a.state)};g.u(P8,g.ZZ);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Ik=g.Hb(a,this.u,this),g.$Z(this,g.Pc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.yc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.ph=function(a){return"cast-selector-receiver"===a?"Cast...":this.Ik[a].name};
P8.prototype.He=function(a){g.ZZ.prototype.He.call(this,a);this.J.setOption("remote","currentReceiver",this.Ik[a]);this.Ua.gb()};g.u(Q8,g.AS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.iC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script")};OJa(b,a);this.subscriptions.push(g.Ko("yt-remote-before-disconnect",this.DM,this));this.subscriptions.push(g.Ko("yt-remote-connection-change",this.zO,this));this.subscriptions.push(g.Ko("yt-remote-receiver-availability-change",this.xE,this));this.subscriptions.push(g.Ko("yt-remote-auto-connect",this.xO,this));this.subscriptions.push(g.Ko("yt-remote-receiver-resumed",
this.wO,this));this.subscriptions.push(g.Ko("mdx-privacy-popup-confirm",this.UP,this));this.subscriptions.push(g.Ko("mdx-privacy-popup-cancel",this.TP,this));this.subscriptions.push(g.Ko("mdx-manual-pairing-popup-ok",this.JJ,this));this.xE()};
g.k.load=function(){this.player.cancelPlayback();g.AS.prototype.load.call(this);this.Th=new I8(this,this.player,this.ub);var a=(a=TJa())?a.currentTime:0;var b=E8()?new $7(z8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.Hc(a);YJa(this,this.Ac,this.Ac);g.S0(this.player.app,6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.bk=this.lh;g.bg(this.Th,this.ub);this.ub=this.Th=null;g.AS.prototype.unload.call(this);g.S0(this.player.app,5);R8(this)};
g.k.aa=function(){g.Lo(this.subscriptions);g.AS.prototype.aa.call(this)};
g.k.zi=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Th.dD.apply(this.Th,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.pe};
g.k.II=function(){return this.loaded?this.Th.suggestion:null};
g.k.ii=function(){return this.ub?a8(this.ub).ii:!1};
g.k.hasNext=function(){return this.ub?a8(this.ub).hasNext:!1};
g.k.Hc=function(a,b){this.uC=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.uC};
g.k.getProgressState=function(){var a=a8(this.ub),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ne():!a.isAdPlaying()&&this.player.ne(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+U7(a):a.D,isAtLiveHead:1>=(a.C?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.N,seekableEnd:a.C?a.B+U7(a):a.B,seekableStart:0<a.F?a.F+
U7(a):a.F}};
g.k.nextVideo=function(){this.ub&&this.ub.nextVideo()};
g.k.Tt=function(){this.ub&&this.ub.Tt()};
g.k.DM=function(a){1===a&&(this.by=this.ub?a8(this.ub):null)};
g.k.zO=function(){var a=E8()?new $7(z8(),void 0):null;if(a){var b=this.bk;this.loaded&&this.unload();this.ub=a;this.by=null;b.key!==this.lh.key&&(this.bk=b,this.load())}else g.ag(this.ub),this.ub=null,this.loaded&&(this.unload(),(a=this.by)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.xE=function(){this.Ik=[this.lh].concat(QJa());var a=A8()||this.lh;S8(this,a);this.player.va("onMdxReceiversChange")};
g.k.xO=function(){var a=A8();S8(this,a)};
g.k.wO=function(){this.bk=A8()};
g.k.UP=function(){this.Up=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.TP=function(){this.Up=!1;R8(this);S8(this,this.lh);this.bk=this.lh;G8=!1;H8=null;this.player.playVideo()};
g.k.JJ=function(){this.Us=!0;R8(this);g.tt("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.je=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ik;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():S8(this,b)),this.loaded?this.bk:this.lh;case "quickCast":return 2===this.Ik.length&&"cast-selector-receiver"===this.Ik[1].key?(b&&Q7(),!0):!1}};
g.k.Uy=function(){this.ub.Uy()};
g.k.Dh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.CX.remote=Q8;})(_yt_player);
